Repository uepb-campusvii-computacao/EventFlow_Backend, pull requests merged in 2025-03, with the labels that each got.

#27 feat: add card payment method
  src/controllers/EventController.ts
  src/repositories/EventRepository.ts
  src/repositories/UserEventRepository.ts
  src/repositories/UserInscricaoRepository.ts
  src/services/payments/createPaymentUserRegistration.ts
Labels: enhancement

#41 fix: conserta nome de rotas.
  src/services/payments/createPaymentUserRegistration.ts
Labels: bug

#42 test: checagem de retorno do mercado pago.
  src/controllers/UserController.ts
Labels: bug

#44 debug: console.log do action.
  src/controllers/UserController.ts
Labels: enhancement

#46 Master merge dev
  prisma/migrations/20250320040509_add_detalhes_de_pagamento_no_user_inscricao_e_add_mais_valores_ao_enum_statuspagamento/migration.sql
  prisma/schema.prisma
  src/controllers/UserController.ts
  src/repositories/UserInscricaoRepository.ts
  src/routes/public/BatchPublicRoutes.ts
  src/services/payments/createPaymentUserRegistration.ts
  src/services/payments/getPayment.ts
Labels: bug, enhancement

#47 feat: adiciona novo retorno ao eventController.
  src/controllers/EventController.ts
Labels: enhancement

#48 Dev merge com Master
  src/controllers/EventController.ts
Labels: enhancement
